### ISSUE TITLE
Dependency on opencv-python

### ISSUE THREAD

**Issue by Erotemic** [Kitware/pybsm#1]
This mirrors an issue reported in https://github.com/Kitware/nrtk/issues/2

See the previous issue for details, but the upshot is that `opencv-python` does not play nice with `opencv-python-headless` and library packages should try to avoid forcing the user into one or the other. The best way I know how to do this is via "extras", but maybe others can brainstorm better ways?

**Comment by bjrichardwebster** [comment]
The fix should be in now as of this [commit](https://github.com/Kitware/pybsm/commit/47b4698b1934390883a5121efd2b16f7167bc551), and was released in `pybsm==0.7.0`. Closing the Issue, please re-open if the issue persists.
